### ISSUE TITLE
Support for Kotlin Script Gradle files

### ISSUE THREAD

**Issue by weverb2** [bitrise-steplib/steps-change-android-versioncode-and-versionname#14]
Using this step with a build.gradle.kts produces the following output:

```
* What went wrong:
Script compilation error:
  Line 31:         versionCode 440
                               ^ Unexpected tokens (use ';' to separate expressions on the same line)
1 error
```

In kts files, the versionCode should look like this:

```
versionCode = 440
```

I can work around this for now, but it would be a good feature for the step!

**Comment by bitce** [comment]
Hi @weverb2,

That makes perfect sense! As a small suggestion, I'd say you should create a [feature request about this on our Discuss](https://discuss.bitrise.io/c/feature-request)! The reason is that people can vote for it there and we regularly check it, so there's a lot higher chance of us implementing this sooner :)

**Comment by thomasflad** [comment]
Same problem here

**Comment by trapacska** [comment]
Hey @thomasflad, @weverb2 !

This release should fix this problem, please check and let us know if it is fixed: https://github.com/bitrise-steplib/steps-change-android-versioncode-and-versionname/releases/tag/1.2.0

🚀

**Comment by mirsaidoff** [comment]
I am having issues also. After migrating to Kotlin-DSL (gradle files), it says `change-versioncode-and-versionname` failed

**Comment by bitce** [comment]
Hi @mirsaidoff! Can you please send an URL about this failing build our way?
