### ISSUE TITLE
Using a variable for new_version_code does not work in bitrise cli

### ISSUE THREAD

**Issue by tstrijdhorst** [bitrise-steplib/steps-change-android-versioncode-and-versionname#26]
When I set the new_version_code to `$BITRISE_BUILD_NUMBER` in the GUI it works perfectly when executing workflow. However when I copy the bitrise.yml to my local machine and use the CLI there is no `new_version_code` setting in the bitrise.yml.

Furthermore, if I manually add `new_version_code: "$BITRISE_BUILD_NUMBER"` it will still not work. However if I fill in a random int like `23` it will work perfectly.

Am I doing something wrong or is there a bug on your side here?

**Comment by fabiendem** [comment]
Have you tried without quotes?
`new_version_code: $BITRISE_BUILD_NUMBER`

**Comment by bitce** [comment]
How do you set this in the first place? Can you show us the relevant snippet of yml?

**Comment by jacky-ew** [comment]
Previous builds was fine, the version increment following the workflow.
Recent build was not, the version and build number does not increase following the workflow, i manually changed it and rebuild, the built was success (previous ones failed because it was the same version/build as google playstore) but it produce an apk with last version number, is this a bug?

**Comment by bitce** [comment]
Hi @jacky-ew please include an URL to the build here so we can take a look. Thanks!
